# -*- coding: utf-8 -*-
"""AI Hugging Face API (Success)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14EBFTy-RHBSGM01b8nT_BkQmKbLQUONR

### Store Hugging Face API Key

To securely use your Hugging Face API key, please store it in Colab's secrets manager. Click the "🔑" icon in the left sidebar, add a new secret, and name it `HF_TOKEN`. Paste your Hugging Face API key as the value.
"""

# # Import the necessary library for securely accessing secrets
# from google.colab import userdata

# # Retrieve the Hugging Face API token from Colab secrets
# HF_TOKEN = userdata.get('HF_TOKEN')

"""## Creating a Web API with Flask

To "create a website with an API model HF" as you requested, we can use a web framework like Flask to expose your Hugging Face model via a simple API endpoint. This allows other applications or web pages to send requests to your Colab notebook and receive responses from the model.
"""

# Install Flask, a lightweight web framework for Python
!pip install Flask

# Install Flask-CORS to handle cross-origin requests
!pip install Flask-Cors

import os
!pip install -q groq
from groq import Groq
from google.colab import userdata

try:
    # Securely retrieve Groq API Key from secrets
    GROQ_API_KEY = userdata.get('GROQ_API_KEY')
    groq_client = Groq(api_key=GROQ_API_KEY)
    print("✅ Groq API configured successfully.")
except userdata.SecretNotFoundError:
    print("❌ Lỗi: Không tìm thấy 'GROQ_API_KEY' trong Secrets.")
    print("Vui lòng thêm key vào mục 🔑 bên trái với tên GROQ_API_KEY và bật quyền truy cập.")
except Exception as e:
    print(f"❌ Đã xảy ra lỗi: {e}")

from flask import Flask, request, jsonify, make_response
import io
from flask_cors import CORS, cross_origin
import json
import pandas as pd
import psycopg2
from groq import Groq
from google.colab import userdata

# Configuration fetched from Secrets manager
try:
    DATABASE_URL = userdata.get('DATABASE_URL')
    GROQ_API_KEY = userdata.get('GROQ_API_KEY')
    groq_client = Groq(api_key=GROQ_API_KEY)
except Exception as e:
    print(f"⚠️ Warning: Secure load failed: {e}")
    DATABASE_URL = None
    groq_client = None

def get_db_connection():
    if not DATABASE_URL: return None
    try:
        conn = psycopg2.connect(DATABASE_URL)
        return conn
    except Exception as e:
        return None

def analyze_report(report_data):
    if not groq_client: return "Error: API Key not configured."
    try:
        prompt = f"Hãy phân tích báo cáo quét bảo mật sau đây bằng tiếng Việt: {str(report_data)}"
        completion = groq_client.chat.completions.create(
            model="llama-3.3-70b-versatile",
            messages=[{"role": "user", "content": prompt}],
            temperature=0.5,
            max_tokens=1024
        )
        ai_summary = completion.choices[0].message.content
    except Exception as e:
        ai_summary = f"Groq Analysis failed: {str(e)}"

    conn = get_db_connection()
    if conn:
        try:
            with conn.cursor() as cur:
                cur.execute("INSERT INTO reports (report_data, summary) VALUES (%s, %s)", (str(report_data), ai_summary))
                conn.commit()
        finally: conn.close()
    return ai_summary

app = Flask(__name__)
CORS(app)

@app.route('/generate', methods=['POST', 'OPTIONS'])
@app.route('/upload-report', methods=['POST', 'OPTIONS'])
def handle_request():
    if request.method == 'OPTIONS': return make_response(("", 204))
    data = request.get_json(silent=True)
    content = data.get('prompt') or data.get('text') if data else None
    if content:
        summary = analyze_report(content)
        return jsonify({'status': 'success', 'summary': summary})
    return jsonify({'error': 'No data provided'}), 400

print("✅ Flask 'app' instance created with secure configuration.")

# This cell is no longer needed as CORS initialization has been moved.
# Please restart the Colab runtime and run all cells from the beginning.

"""### Set up ngrok for Public Access

To expose your local Flask server to the internet without blocking notebook execution, we'll use `ngrok`. You'll need an `ngrok` authentication token.

1. Go to [ngrok.com](https://ngrok.com/) and sign up for a free account.
2. Get your Authtoken from the ngrok dashboard.
3. In Colab's secrets manager (click the "🔑" icon on the left), add a new secret named `NGROK_AUTH_TOKEN` and paste your ngrok authtoken as the value.
"""

# Install pyngrok to interact with ngrok
!pip install pyngrok

from pyngrok import ngrok, conf
from google.colab import userdata

# Get ngrok authtoken from Colab secrets
NGROK_AUTH_TOKEN = userdata.get('NGROK_AUTH_TOKEN')

# Set the authtoken (this will write to ~/.ngrok2/ngrok.yml)
conf.get_default().auth_token = NGROK_AUTH_TOKEN

"""## Run the Flask API

This cell will start the Flask server. It will run on `0.0.0.0:5000` within the Colab environment. You can then make requests to it from other cells in this notebook. If you need to expose it to the public internet, you would typically use a tool like `ngrok`, but for testing within Colab, this setup is sufficient.
"""

import threading
import os
from pyngrok import ngrok, conf
from google.colab import userdata

# Restart server logic
def run_flask():
    app.run(port=5000, use_reloader=False, debug=False)

try:
    conf.get_default().auth_token = userdata.get('NGROK_AUTH_TOKEN')
    os.system("fuser -k 5000/tcp")
    os.system("fuser -k 8000/tcp")
    ngrok.kill()

    threading.Thread(target=run_flask, daemon=True).start()

    public_url = ngrok.connect(5000).public_url
    frontend_public_url = ngrok.connect(8000).public_url

    print(f"✅ API URL: {public_url}")
    print(f"✅ Frontend URL: {frontend_public_url}")
except Exception as e:
    print(f"❌ Failed to start: {e}")

"""## Example of API Usage

Once the Flask app is running in the previous cell, you can send POST requests to the `/generate` endpoint using the `requests` library. This example demonstrates how to call your newly created API.
"""



import requests
import json
import os

# Retrieve the current ngrok URL
api_url_base = globals().get('public_url') or os.environ.get('NGROK_PUBLIC_URL')

if not api_url_base:
    print("Error: ngrok public URL not found. Please re-run cell 54a0db4d.")
else:
    api_url = f"{api_url_base}/generate"
    print(f"Testing API Endpoint: {api_url}")

    payload = {'prompt': 'Hãy tóm tắt rủi ro bảo mật của việc sử dụng mật khẩu yếu.'}
    headers = {'Content-Type': 'application/json'}

    try:
        response = requests.post(api_url, data=json.dumps(payload), headers=headers)
        response.raise_for_status()
        result = response.json()
        print("\n--- Gemini Analysis Result ---")
        print(result.get('summary') or result.get('generated_text'))
    except Exception as e:
        print(f"An error occurred: {e}")
        print("Note: If you get a 404, please ensure you restarted the Flask server in cell 54a0db4d.")

"""## Debugging the Hugging Face API Call

To diagnose the 500 error from the Flask app, let's directly test the `OpenAI` client call that the Flask app uses. This will help us confirm if the `HF_TOKEN`, `base_url`, and `model` are correctly configured and functional.
"""

from openai import OpenAI

# Assuming HF_TOKEN is already loaded from Colab secrets

try:
    debug_client = OpenAI(
        base_url="https://router.huggingface.co/v1",
        api_key=HF_TOKEN,
    )

    debug_completion = debug_client.chat.completions.create(
        model="deepseek-ai/DeepSeek-V4-Pro:novita",
        messages=[
            {
                "role": "user",
                "content": "What is the capital of Japan?"
            }
        ],
    )

    print("Direct API call successful!")
    print("Response:", debug_completion.choices[0].message.content)

except Exception as e:
    print(f"Direct API call failed with error: {e}")
    print("Please check your HF_TOKEN, model name, and network connectivity.")

"""### Creating a Simple HTML/JavaScript Frontend

Now that your API is running and accessible, let's create a basic HTML page with JavaScript to interact with it. This will demonstrate how to send a prompt to your API and display the generated response.

We will create two files:
1.  `index.html`: The main web page with an input field and a display area.
2.  `script.js`: The JavaScript code that handles sending requests to your API.
"""

html_content = '''
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>AI Security Analyzer</title>
    <style>
        body { font-family: sans-serif; margin: 20px; background: #f4f4f4; }
        .box { background: white; padding: 20px; border-radius: 8px; max-width: 600px; margin: auto; box-shadow: 0 2px 5px rgba(0,0,0,0.1); }
        textarea { width: 100%; height: 100px; margin: 10px 0; }
        button { width: 100%; padding: 10px; background: #007bff; color: white; border: none; cursor: pointer; margin-top: 5px; }
        #result { margin-top: 20px; padding: 15px; background: #e9ecef; white-space: pre-wrap; display: none; }
    </style>
</head>
<body>
    <div class="box">
        <h2>🛡️ AI Security Analyzer</h2>
        <textarea id="txtInput" placeholder="Dán nội dung báo cáo vào đây..."></textarea>
        <button onclick="analyze('text')">Phân tích Văn bản</button>
        <hr>
        <input type="file" id="fileInput">
        <button onclick="analyze('file')">Tải tệp & Phân tích</button>
        <div id="result"></div>
    </div>
    <script src="script.js"></script>
</body>
</html>
'''
with open('index.html', 'w') as f: f.write(html_content)

js_content = f'''
const BASE_URL = "{public_url}";
console.log("API Base URL:", BASE_URL);

async function analyze(type) {{
    const resDiv = document.getElementById('result');
    resDiv.style.display = 'block';
    resDiv.textContent = 'Đang phân tích...';

    let body, headers = {{}};
    if (type === 'text') {{
        const textInput = document.getElementById('txtInput').value;
        if (!textInput) {{
            resDiv.textContent = 'Vui lòng nhập văn bản!';
            return;
        }}
        body = JSON.stringify({{ text: textInput }});
        headers = {{ 'Content-Type': 'application/json' }};
    }} else {{
        const fileInput = document.getElementById('fileInput');
        if (!fileInput.files[0]) {{
            resDiv.textContent = 'Vui lòng chọn một tệp!';
            return;
        }}
        body = new FormData();
        body.append('file', fileInput.files[0]);
    }}

    try {{
        const resp = await fetch(`${{BASE_URL}}/upload-report`, {{
            method: 'POST',
            headers: headers,
            body: body
        }});

        const contentType = resp.headers.get("content-type");
        if (!contentType || !contentType.includes("application/json")) {{
            throw new Error("Server không trả về JSON. Có thể server chưa chạy hoặc lỗi ngrok.");
        }}

        const data = await resp.json();
        if (!resp.ok) throw new Error(data.error || 'Lỗi server');

        resDiv.innerHTML = `<div style="white-space: pre-wrap;">${{data.summary}}</div>`;
    }} catch (e) {{
        resDiv.textContent = 'Lỗi: ' + e.message;
        console.error('Fetch Error:', e);
    }}
}}
'''
with open('script.js', 'w') as f: f.write(js_content)

"""### Serving the Frontend Locally

To view your HTML frontend, we'll start a simple HTTP server in Colab. This server will make `index.html` and `script.js` accessible.
"""

import threading
import socketserver
from http.server import SimpleHTTPRequestHandler
import time
import os

PORT = 8000

class CustomHandler(SimpleHTTPRequestHandler):
    def do_GET(self):
        # Serve index.html when root is requested
        if self.path == '/':
            self.path = '/index.html'
        return SimpleHTTPRequestHandler.do_GET(self)

def start_server():
    # Ensure the server runs from the directory where index.html and script.js are located
    current_dir = os.getcwd()
    os.chdir('/content/')

    # Allow port reuse to prevent 'Address already in use' errors if the kernel is restarted quickly
    socketserver.TCPServer.allow_reuse_address = True
    try:
        with socketserver.TCPServer(('', PORT), CustomHandler) as httpd:
            print(f"Serving frontend at http://localhost:{PORT}")
            httpd.serve_forever()
    except OSError as e:
        print(f"Error starting frontend server on port {PORT}: {e}")
        print("This often means the port is already in use. Please try restarting the Colab runtime (Runtime -> Restart runtime...) and re-running all cells.")
    except Exception as e:
        print(f"An unexpected error occurred while starting the frontend server: {e}")
    finally:
        # Change back to the original directory
        os.chdir(current_dir)

# Start the server in a separate thread so it doesn't block the notebook
server_thread = threading.Thread(target=start_server)
server_thread.daemon = True  # Allow the program to exit even if the thread is still running
server_thread.start()

# Give the server a moment to start and bind before ngrok tries to connect
time.sleep(2)

print(f"Frontend server thread initiated on port {PORT}.")
print("Please check the output above for any server startup errors.")

"""### How to Access Your Frontend

Since the frontend server is running locally within your Colab environment, accessing it can be done in a few ways:

1.  **Download and Run Locally:** The easiest way is to download `index.html` and `script.js` from your Colab files panel (on the left sidebar, navigate to the `/content/` directory). Then, simply open `index.html` in your web browser.

2.  **Using a Second ngrok Tunnel (Advanced):** If you want to access the frontend from a public URL like your API, you would need to set up *another* ngrok tunnel for port `8000`. This is generally more involved but possible:
    ```python
    # Example: Run this in a new cell if you want to expose the frontend publicly
    from pyngrok import ngrok
    ngrok.kill() # Kill existing tunnels if necessary
    frontend_tunnel = ngrok.connect(PORT)
    print(f"Frontend public URL: {frontend_tunnel.public_url}")
    ```

For now, I recommend downloading the files and opening `index.html` directly in your browser. Ensure your Colab notebook (and thus your API) remains running while you test the frontend!

### Exposing the Frontend with ngrok

To access your frontend directly via a public URL, we'll set up a second `ngrok` tunnel for the local HTTP server running on port `8000`.
"""

from pyngrok import ngrok, conf
import os
from google.colab import userdata

# Ensure NGROK_AUTH_TOKEN is set for this new tunnel if not already done in the session
# This assumes the NGROK_AUTH_TOKEN has been set earlier in the notebook
# If it hasn't, you would need to retrieve it from Colab secrets again.
if not conf.get_default().auth_token:
    NGROK_AUTH_TOKEN = userdata.get('NGROK_AUTH_TOKEN')
    conf.get_default().auth_token = NGROK_AUTH_TOKEN

# Kill any existing ngrok tunnels on this port (if a previous frontend tunnel was opened and closed improperly)
# We specifically kill tunnels on port 8000 to avoid affecting the Flask API tunnel on port 5000
for tunnel in ngrok.get_tunnels():
    if tunnel.data['config']['addr'] == 'http://localhost:8000':
        ngrok.disconnect(tunnel.public_url)
        print(f"Disconnected existing ngrok tunnel for frontend: {tunnel.public_url}")


# Start a new ngrok tunnel for the frontend server on port 8000
# Use a different authtoken if the previous one is already consumed by the Flask app
# For simplicity, we reuse the same authtoken, ngrok handles multiple tunnels per authtoken.
frontend_tunnel = ngrok.connect(PORT)
frontend_public_url = frontend_tunnel.public_url
print(f"Frontend public URL: {frontend_public_url}")
print(f"You can now access your frontend at: {frontend_public_url}")

# Note: This public URL will be different each time ngrok is started.

import requests
import time

# Re-check the API and Frontend status
print(f"Checking API status at: {public_url}")
try:
    # Simple health check to the root or a test endpoint
    test_payload = {'prompt': 'Health check'}
    resp = requests.post(f"{public_url}/generate", json=test_payload, timeout=5)
    if resp.status_code == 200:
        print("✅ API is Online and responding correctly.")
    else:
        print(f"⚠️ API returned status code: {resp.status_code}")
except Exception as e:
    print(f"❌ API Connection Error: {e}")

print(f"\nFrontend is available at: {frontend_public_url}")
print("If the website doesn't load, please ensure cell 54a0db4d and b8cf42c4 are both running.")

"""### Database Integration (Neon PostgreSQL)

We will now set up the connection to your Neon database and prepare a function for report analysis.
"""

!pip install psycopg2-binary

import psycopg2
from google.colab import userdata

# Use userdata to avoid exposing credentials in the cell
try:
    DATABASE_URL = userdata.get('DATABASE_URL')
except Exception:
    DATABASE_URL = None

def get_db_connection():
    if not DATABASE_URL:
        print("Error: DATABASE_URL not found in Secrets.")
        return None
    try:
        conn = psycopg2.connect(DATABASE_URL)
        return conn
    except Exception as e:
        print(f"Error connecting to the database: {e}")
        return None

# Test connection
connection = get_db_connection()
if connection:
    print("Successfully connected to Neon PostgreSQL (Secured)!")
    connection.close()

"""### Report Analysis Logic

This section defines how reports (e.g., from the Multi-Scanner Correlation Plugin) will be analyzed and potentially stored in the database.
"""

def analyze_report(report_data, use_ai=True):
    """
    Analyzes report data using code logic or DeepSeek AI.
    Stores both raw data and AI summary in the Neon database.
    """
    ai_summary = ""
    if use_ai:
        try:
            prompt = f"Analyze this security scan report and provide a concise professional summary with key risks and recommendations in Vietnamese: {str(report_data)}"
            completion = client.chat.completions.create(
                model="deepseek-ai/DeepSeek-V4-Pro:novita",
                messages=[{"role": "user", "content": prompt}],
            )
            ai_summary = completion.choices[0].message.content
        except Exception as e:
            ai_summary = f"AI Analysis failed: {str(e)}"
    else:
        ai_summary = f"Processed {len(report_data) if isinstance(report_data, list) else 'text'} report."

    # Saving to Neon DB
    conn = get_db_connection()
    if conn:
        try:
            with conn.cursor() as cur:
                insert_query = "INSERT INTO reports (report_data, summary) VALUES (%s, %s) RETURNING id;"
                cur.execute(insert_query, (str(report_data), ai_summary))
                report_id = cur.fetchone()[0]
                conn.commit()
                print(f"AI Analysis saved with ID: {report_id}")
        except Exception as e:
            print(f"Error saving to database: {e}")
        finally:
            conn.close()

    return ai_summary

def create_reports_table():
    """Creates the reports table in the Neon database if it doesn't already exist."""
    conn = get_db_connection()
    if conn:
        try:
            with conn.cursor() as cur:
                create_table_query = """
                CREATE TABLE IF NOT EXISTS reports (
                    id SERIAL PRIMARY KEY,
                    report_data TEXT NOT NULL,
                    summary TEXT,
                    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
                );
                """
                cur.execute(create_table_query)
                conn.commit()
                print("Table 'reports' is ready.")
        except Exception as e:
            print(f"Error creating table: {e}")
        finally:
            conn.close()

# Execute the table creation
create_reports_table()

def analyze_report(report_data, use_ai=True):
    """
    Analyzes report data using Groq API (Llama 3).
    Stores both raw data and AI summary in the Neon database.
    """
    ai_summary = ""
    if use_ai:
        try:
            prompt = f"Hãy phân tích báo cáo quét bảo mật sau đây và cung cấp một bản tóm tắt chuyên nghiệp, ngắn gọn bao gồm các rủi ro chính và khuyến nghị bằng tiếng Việt: {str(report_data)}"

            completion = groq_client.chat.completions.create(
                model="llama-3.3-70b-versatile",
                messages=[{"role": "user", "content": prompt}],
                temperature=0.5,
                max_tokens=1024
            )
            ai_summary = completion.choices[0].message.content
        except Exception as e:
            ai_summary = f"Groq Analysis failed: {str(e)}"
    else:
        ai_summary = f"Processed {len(report_data) if isinstance(report_data, list) else 'text'} report."

    # Saving to Neon DB
    conn = get_db_connection()
    if conn:
        try:
            with conn.cursor() as cur:
                insert_query = "INSERT INTO reports (report_data, summary) VALUES (%s, %s) RETURNING id;"
                cur.execute(insert_query, (str(report_data), ai_summary))
                report_id = cur.fetchone()[0]
                conn.commit()
                print(f"Analysis saved with ID: {report_id}")
        except Exception as e:
            print(f"Error saving to database: {e}")
        finally:
            conn.close()

    return ai_summary

# Sample report data for Groq Verification
sample_report = [
    {"scanner": "Scanner_A", "vulnerability": "SQL Injection", "severity": "High"},
    {"scanner": "Scanner_B", "vulnerability": "XSS", "severity": "Medium"}
]

print("Verifying analyze_report with Groq (Llama 3)...")
test_summary = analyze_report(sample_report)
print(f"\n--- Groq AI Summary ---\n{test_summary}")

# Query the database to see the last 5 reports saved
import pandas as pd

def view_latest_reports():
    conn = get_db_connection()
    if conn:
        try:
            query = "SELECT id, summary, created_at FROM reports ORDER BY created_at DESC LIMIT 5;"
            df = pd.read_sql_query(query, conn)
            print("--- Latest 5 Reports in Database ---")
            display(df)
        except Exception as e:
            print(f"Error querying database: {e}")
        finally:
            conn.close()

view_latest_reports()

"""# Query the database to see the last 5 reports saved
def view_latest_reports():
    conn = get_db_connection()
    if conn:
        try:
            import pandas as pd
            query = "SELECT id, summary, created_at FROM reports ORDER BY created_at DESC LIMIT 5;"
            df = pd.read_sql_query(query, conn)
            display(df)
        except Exception as e:
            print(f"Error querying database: {e}")
        finally:
            conn.close()

view_latest_reports()
"""