services:
  - type: web
    name: AI-Security-Analyzer-Groq
    runtime: python
    region: oregon
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    healthCheckPath: /healthz
    autoDeployTrigger: commit
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: DATABASE_URL
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: HF_TOKEN
        sync: false
      - key: NGROK_AUTH_TOKEN
        sync: false